const PRODUCTS = [
  {
    id: 1,
    name: "Boho Market Tote",
    category: "bags",
    price: 899,
    originalPrice: 1199,
    rating: 4.8,
    reviews: 43,
    tag: "Bestseller",
    emoji: "👜",
    colors: ["#e07b6b","#7eb8a4","#c9a96e"],
    description: "Spacious handcrafted market tote made from 100% organic cotton. Reinforced handles, natural dye colors, ethically sourced yarn.",
    stock: 5,
    popular: true,
    img: "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=400&q=80"
  },
  {
    id: 2,
    name: "Sunflower Wall Hanging",
    category: "home-decor",
    price: 749,
    originalPrice: null,
    rating: 4.9,
    reviews: 28,
    tag: "New",
    emoji: "🌻",
    colors: ["#e8c96b","#c9a96e","#5c4033"],
    description: "Stunning macramé-inspired crochet wall hanging. A bold sunflower motif on a driftwood rod. Makes every room feel alive.",
    stock: 8,
    popular: true,
    img: "https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=400&q=80"
  },
  {
    id: 3,
    name: "Mini Bear Amigurumi",
    category: "toys",
    price: 549,
    originalPrice: 699,
    rating: 5.0,
    reviews: 67,
    tag: "Top Rated",
    emoji: "🐻",
    colors: ["#c9a96e","#5c4033","#e8c96b"],
    description: "Adorable 15cm hand-stitched bear. Hypoallergenic stuffing. Safe for all ages. Perfect gift or collectible.",
    stock: 12,
    popular: true,
    img: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80"
  },
  {
    id: 4,
    name: "Sage Cropped Cardigan",
    category: "clothing",
    price: 1849,
    originalPrice: 2299,
    rating: 4.7,
    reviews: 19,
    tag: "Limited",
    emoji: "🧥",
    colors: ["#7eb8a4","#8a7bb5","#e07b6b"],
    description: "Cozy sage-green cropped cardigan crocheted in breathable cotton blend. Open-front, relaxed fit, available S–XL.",
    stock: 3,
    popular: false,
    img: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=400&q=80"
  },
  {
    id: 5,
    name: "Dreamcatcher Hair Clips",
    category: "accessories",
    price: 299,
    originalPrice: null,
    rating: 4.6,
    reviews: 52,
    tag: "Popular",
    emoji: "🎀",
    colors: ["#d4799a","#8a7bb5","#e8c96b"],
    description: "Set of 3 delicate crochet hair clips — each a tiny dreamcatcher. Lightweight, boho-chic, and incredibly charming.",
    stock: 20,
    popular: true,
    img: "https://images.unsplash.com/photo-1594897030264-ab7d87efc473?w=400&q=80"
  },
  {
    id: 6,
    name: "Terracotta Clutch Purse",
    category: "bags",
    price: 699,
    originalPrice: 899,
    rating: 4.5,
    reviews: 31,
    tag: "Sale",
    emoji: "👛",
    colors: ["#e07b6b","#c9a96e","#5c4033"],
    description: "A chic mini clutch in earthy terracotta tones. Lined interior, magnetic snap closure, optional detachable strap.",
    stock: 7,
    popular: false,
    img: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&q=80"
  },
  {
    id: 7,
    name: "Boho Plant Pot Sleeve",
    category: "home-decor",
    price: 399,
    originalPrice: null,
    rating: 4.8,
    reviews: 44,
    tag: "Eco",
    emoji: "🪴",
    colors: ["#7eb8a4","#c9a96e","#e07b6b"],
    description: "Dress up your plant babies with these gorgeous crocheted pot sleeves. Fits 4–6 inch pots. Adds warmth to any shelf.",
    stock: 15,
    popular: false,
    img: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400&q=80"
  },
  {
    id: 8,
    name: "Lavender Beach Hat",
    category: "clothing",
    price: 649,
    originalPrice: 799,
    rating: 4.9,
    reviews: 38,
    tag: "Summer Pick",
    emoji: "👒",
    colors: ["#8a7bb5","#d4799a","#e07b6b"],
    description: "Wide-brimmed floppy beach hat in dreamy lavender. Lightweight cotton yarn, UV protective, one-size with adjustable band.",
    stock: 9,
    popular: true,
    img: "https://images.unsplash.com/photo-1521369909029-2afed882baee?w=400&q=80"
  },
  {
    id: 9,
    name: "Rainbow Keychain Set",
    category: "accessories",
    price: 199,
    originalPrice: null,
    rating: 4.7,
    reviews: 88,
    tag: "Gift Idea",
    emoji: "🌈",
    colors: ["#e07b6b","#e8c96b","#7eb8a4","#4a7fa5","#8a7bb5"],
    description: "Pack of 3 mini rainbow crochet keychains. Great as gifts, bag charms, or stocking stuffers. Pure joy in your pocket.",
    stock: 30,
    popular: true,
    img: "https://images.unsplash.com/photo-1561985931-34e4f38fc4d4?w=400&q=80"
  },
  {
    id: 10,
    name: "Chunky Throw Pillow",
    category: "home-decor",
    price: 1099,
    originalPrice: 1399,
    rating: 4.8,
    reviews: 22,
    tag: "Cozy Pick",
    emoji: "🛋️",
    colors: ["#c9a96e","#e07b6b","#7eb8a4"],
    description: "Luxuriously soft chunky crochet throw pillow. 45×45cm with zipper closure and plump insert. Instantly transforms your sofa.",
    stock: 6,
    popular: false,
    img: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400&q=80"
  },
  {
    id: 11,
    name: "Mini Cactus Amigurumi",
    category: "toys",
    price: 449,
    originalPrice: null,
    rating: 4.9,
    reviews: 55,
    tag: "Desk Buddy",
    emoji: "🌵",
    colors: ["#7eb8a4","#e8c96b","#d4799a"],
    description: "Cute 10cm crochet cactus that won't poke you! Perfect desk companion, party favour, or beginner crocheter's dream to own.",
    stock: 18,
    popular: true,
    img: "https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=400&q=80"
  },
  {
    id: 12,
    name: "Ombre Wrap Shawl",
    category: "clothing",
    price: 1249,
    originalPrice: 1599,
    rating: 4.6,
    reviews: 14,
    tag: "Artisan",
    emoji: "🧣",
    colors: ["#d4799a","#8a7bb5","#4a7fa5"],
    description: "Flowing ombre wrap shawl transitioning from blush to lilac to blue. One size fits all. A wearable work of art.",
    stock: 4,
    popular: false,
    img: "https://images.unsplash.com/photo-1594226801341-41427b4e5c22?w=400&q=80"
  }
];
